### PR TITLE
Added linesort two-op operation

### PR DESCRIPTION
**Pull request by tatarize**
#### Description

Adds in a flag for the linesort command to perform two-opt global distance minimization.

#### Checklist

- [ ] feature/fix implemented
- [ ] code formatting ok (`black` and `isort`)
- [ ] `mypy vpype vpype_cli tests` returns no error
- [ ] tests added/updated and `pytest` succeeds
- [ ] documentation added/updated
    - [ ] command docstring and option/argument `help`
    - [ ] README.md updated (Feature Overview)
    - [ ] CHANGELOG.md updated
    - [ ] RTD doc updated and building with no error (`make clean && make html` in `docs/`)

### CODE REVIEW

**Comment by tatarize** [comment]
> vpype -v read test.svg linemerge linesort write t1.svg

```
INFO:root:executing layer processor `linesort` on layer 1 (kwargs: {'no_flip': False, 'two_opt': False})
INFO:root:LineIndex: creating index for 300 lines
INFO:root:LineIndex: creating index for 118 lines
INFO:root:optimize: reduced pen-up (distance, mean, median) from (12750.22643475841, 42.500754782528034, 6.245283127143871) to (5950.841189588275, 19.83613729862758, 4.844412759507364)
INFO:root:layer processor `linesort` execution complete (0.080s)
INFO:root:executing layer processor `linesort` on layer 1337 (kwargs: {'no_flip': False, 'two_opt': False})
INFO:root:LineIndex: creating index for 14 lines
INFO:root:optimize: reduced pen-up (distance, mean, median) from (29.859837039708502, 2.1328455028363216, 1.8746727230260916) to (23.38916720601566, 1.67065480042969, 1.8746727230260916)
INFO:root:layer processor `linesort` execution complete (0.004s)
INFO:root:executing layer processor `linesort` on layer 13379 (kwargs: {'no_flip': False, 'two_opt': False})
INFO:root:LineIndex: creating index for 14 lines
INFO:root:optimize: reduced pen-up (distance, mean, median) from (29.859837039708523, 2.132845502836323, 1.8746727230260958) to (23.389167206015713, 1.6706548004296937, 1.8746727230260958)
INFO:root:layer processor `linesort` execution complete (0.005s)
```
12750.22643475841 -> 5950.841189588275 in 0.080s


> vpype -v read test.svg linemerge linesort -t write t1.svg
```
INFO:root:executing layer processor `linesort` on layer 1 (kwargs: {'two_opt': True, 'no_flip': False})
INFO:root:optimize: reduced pen-up (distance, mean, median) from (12750.22643475841, 42.500754782528034, 6.245283127143871) to (5361.155188942335, 17.87051729647445, 4.890580975063153)
INFO:root:layer processor `linesort` execution complete (6.169s)
INFO:root:executing layer processor `linesort` on layer 1337 (kwargs: {'two_opt': True, 'no_flip': False})
INFO:root:optimize: reduced pen-up (distance, mean, median) from (29.859837039708502, 2.1328455028363216, 1.8746727230260916) to (23.38916720601566, 1.67065480042969, 1.8746727230260916)
INFO:root:layer processor `linesort` execution complete (0.005s)
INFO:root:executing layer processor `linesort` on layer 13379 (kwargs: {'two_opt': True, 'no_flip': False})
INFO:root:optimize: reduced pen-up (distance, mean, median) from (29.859837039708523, 2.132845502836323, 1.8746727230260958) to (23.389167206015713, 1.6706548004296937, 1.8746727230260958)
INFO:root:layer processor `linesort` execution complete (0.005s)
```
12750.22643475841 -> 5361.155188942335 in 6.169s

Squeezed out 11% in 77x the time.

**Comment by tatarize** [comment]
It's 20% less distance at a cost of 11x the time. Rewrote it in numpy. So a 12k pen distance dropped to a 5.9k then with 10x the time to do that it dropped 20% more to 4.9k. Taking 0.08 seconds initially to 0.93 seconds.

**Comment by tatarize** [comment]
@abey79 I'm not sure how to fix the codecov stuff. It yells at me anytime I try to mess with the testing stuff. I assume any test that invokes it would fix that.

**Comment by tatarize** [comment]
@abey79 I failed to jump through the required hoops, but this is pretty solid code. I am in no way attached to this integration, but  much significant improvements to linesort might be code worth having.

**Comment by abey79** [comment]
Yeah, I plan to integrate this in the next release. Hope to be able do that inside of the next couple of weeks.

**Pull request merged**
