### PR TITLE
Add support for global and per-layer metadata

### LINKED ISSUE #145: Consider preserving stroke color
Title says it all. I got vpype working and was hoping to use the crop feature, but my plots are multi-color and vpype crops fine, but blows away my colors. Is this a challenging feature to add?

### PR DESCRIPTION
**Pull request by abey79**
#### Description

This PR introduce per-layer and global metadata to the vpype pipeline. Metadata takes the form of a free-form set of properties identified by a string. Supported types include `str`, `int`, `float`, and `vpype.Color` (as `color` in the UI).

Low-level inspection, modification and deletion of both global and layer properties can be done with a new set of low-level commands prefixed by `prop-`:
```
# global operations
propset -g -t int my_prop 18
proplist -g
propget -g my_prop
propdel -g my_prop
propclear -g

# per layer(s) operations
propset -l 1 -t str my_prop my_value
proplist -l 1
propget -l 1 my_prop
propdel -l all my_prop
propclear -l 1
```

Properties whose name is prefixed by `vp:` are used by vpype for a number of features, some of which are newly introduced in this PR. Such properties are referred to as "system properties".

Layer system properties:
- `vp:color` (`color`): the color to be used for the layer
- `vp:pen_width` (`float`): the pen width to be used for the layer
- `vp:name` (`float`): the name of the layer (in the `inkscape:label` SVG attribute sense)

Global system properties:
- `vp:page_size`: the page size (formerly stored as an instance attribute to the `vp.Document` class 

The `show` and `write` command now take into account the above layer system properties. The page size related commands (`pagesize` and `layout`) now act on the `vp:page_size` global system property.

New, high-level commands are introduced to interact with the new layer system properties:
- `name`: sets the name of a given layer
- `color`: changes the color for a given layer
- `penwidth`: changes the pen-width of a given layer
- `pens`: apply a pre-defined set of per-layer name, color, and/or pen width to the pipelines, based on a template defined in a config file (`rgb` and `cmyk` templates are bundled in the new config file)

In addition to populating the system properties (when possible), the `read` command now extracts a number of SVG attributes and stores them as properties (prefixed with `svg:`). Optionally, the `write` command can attempt to restore those properties when possible. Note: since properties are per layer, SVG attributes are saved only if they are shared by *all* the geometries contained in a given layer.

The layer operation commands are updated to handle metadata:
- When a single source layer is specified and `--prob` is not used, the `lcopy` and `lmove` commands now copy the source layer's properties to the destination layer (possibly overwriting existing properties).
- When `--prob` is not used, the `lswap` command now swaps the layer properties as well.
- These behaviours may be disabled with the `--no-prop` option.

API changes:
- `vpype.Document` and `vpype.LineCollection` have been extended to support operation on their metadata (through the use of a mix-in class)

Other changes:
- the bundled config file is renamed to `vpype_config.toml` (since it's no longer specific to HPGL features)
- `stat` command now display all the metadata in the pipeline
- added a warning when a layer passed to `--layer` doesn't exist
- tests: added a few SVG test cases
- doc: several addition/changes relative to metadata
- doc: some minor fixes

Fixes #145 and #213 

TODO:
- [x] populate vp:name in `read_[multilayer_]svg()`
- [x] finalize commands
- [x] add document-level metadata
- [x] change link to config file in cookbook.rst
- [x] test `read -m`
- [x] use metadata in `write_svg()`
- [ ] ~test: add viewer tests depending on metadata~ (#375)
- [x] doc: add metadata paragraph in fundamentals
- [x] doc: add cookbook chapters (incl custom pen config)
- [x] readme command list
- [x] finalise vpype viewer
- [x] `propset` must accept units for float/int values

#### Checklist

- [x] feature/fix implemented
- [x] code formatting ok (`black` and `isort`)
- [x] `mypy vpype vpype_cli tests` returns no error
- [x] tests added/updated and `pytest` succeeds
- [x] documentation added/updated
    - [x] command docstring and option/argument `help`
    - [x] README.md updated (Feature Overview)
    - [x] CHANGELOG.md updated
    - [x] RTD doc updated and building with no error (`make clean && make html` in `docs/`)

### CODE REVIEW

**Comment by EmmaSimon** [comment]
Not sure if I should make this a feature request somewhere else, but it might make sense to add support for changing the background color of the SVG as part of this, since this will enable stroke color changes.

**Comment by abey79** [comment]
@EmmaSimon can you elaborate? Why would the background color be important to change stroke color?

**Comment by EmmaSimon** [comment]
@abey79 Er, sorry, I phrased that weird. I just meant that I want the ability to change background color, in addition to stroke color.

**Comment by abey79** [comment]
@EmmaSimon I've not planned "global" metadata yet, but that might be a good reason to think about it. I have a rather strict policy favouring feature that make sens for plotter application but custom background color makes sense to prefix plots on colored paper.

**Comment by EmmaSimon** [comment]
Right, that was my reasoning, stroke color drastically changes how plots can look, and paper color drastically changes how stroke color looks! So it would be nice to see that while you're designing the sketch.

**Comment by abey79** [comment]
@EmmaSimon as you might have seen, everything is ready for custom background colour support. I won't however include it in the present PR.

**Pull request merged**
