### PR TITLE
Feature splitdist

### PR DESCRIPTION
**Pull request by LoicGoulefert**
#### Description

Add `splitdist` command to vpype_cli.

#### Checklist

- [x] feature/fix implemented
- [x] code formatting ok (`black` and `isort`)
- [x] `mypy` returns no error
- [x] tests added/updated and `pytest` succeeds
- [x] documentation added/updated
    - [ ] command docstring and option/argument `help`
    - [x] README.md updated (Feature Overview)
    - [x] CHANGELOG.md updated
    - [ ] added new command to `reference.rst`
    - [ ] RTD doc updated and building with no error (`make clean && make html` in `docs/`)

####  Manual testing

<details>
  <summary>Base SVGs</summary>
  
  Single layer base SVG
  circle_grid_d1cm

  Multilayer base SVG
  multilayer_circle_grid_d1cm
</details>

<details>
  <summary>splitdist 2cm on single layer SVG</summary>

  `vpype read circle_grid_d1cm.svg splitdist 2cm show`
  splitdist_singlelayer_2cm
</details>

<details>
  <summary>splitdist 12cm on single layer SVG</summary>

   `vpype read circle_grid_d1cm.svg splitdist 12cm show`
   splitdist_singlelayer_12cm
</details>

<details>
  <summary>splitall, splitdist 2cm on single layer SVG</summary>

  `vpype read circle_grid_d1cm.svg splitall splitdist 2cm show`
  splitall_splitdist_singlelayer_2cm
</details>

<details>
  <summary>splitdist 2cm on multilayer SVG, all layers</summary>
  
  vpype read multilayer_circle_grid_d1cm.svg splitdist 2cm show
  splitdist_multilayer_all_2cm
</details>

<details>
  <summary>splitdist 2cm on multilayer SVG, only layer 2</summary>

  `vpype read multilayer_circle_grid_d1cm.svg splitdist -l 2 2cm show`
  splitdist_multilayer_l2_2cm
</details>

### CODE REVIEW

**Comment by abey79** [comment]
Fixes #337

**Comment by andeecollard** [comment]
This looks amazing! How could I use this to replenish paint like watercolorbot? Installing the master now

**Comment by andeecollard** [comment]
thanks @abey79 and @LoicGoulefert brilliant stuff!
I've wanted this for such a long time! The only thing I'm missing is the reload routine. I could probably bodge together something manually with the svg but this obviously isn't ideal.

Is there anyway to process the output of this or even better add an argument where after each layer the brush returns to the predefined palette location/ the performs a macro? Could you make a custom .toml profile with artwork/ palette locations?

**Comment by andeecollard** [comment]
Thinking about this further the creation of lots and lots you layers might get a bit unwieldy. How else could you split the layer but keep it together in a group? 

My use case is to make paintings. I currently use the watercolorbot Inkscape extension. I want to paint complex designs with lots of hatching and for the paint brush to reload every 30cm. With splitdist I can get the location of where each reload should take place but a lot of layers. 
Is there another way to mark these breaks? Groups within the layer? e.g the original layer heiracy remain the same 1,2,3,4, with the break groups within each layer?

Sorry for all the questions! This is great work

**Comment by abey79** [comment]
Yeah, for your use case maybe we didnt use the right approach.

One alternative could be a command that says "insert content of layer X at the beginning of layer Y and every 30cm thereafter". You'd still have to structure your svg with N layers, one for each color, and then N other layers, one for each well, and then call that new command N times, which isn't great.

That said, am I right to assume that you need manual intervention between each color? Like cleaning/changing the brush at least? It would be relatively easy with a few vpype commands, possibly in a script, to achieve the following workflow:
- split the source file into multiple files, on per layer and one per well
- load each layer file, `splitdist` it, insert corresponding well in between each layer (this can be one big ugly vpype call that I could help you write)

Then you'd manually run each processed file for each color.

**Comment by andeecollard** [comment]
@abey79 yes I agree. I have been playing around with using Shortcuts on the Mac to compose the arguments for vpype and this might help  with the "big ugly vpype call"

I'll do some experiments. splitdist definitely helps with one of the biggest hurdles.

**Comment by abey79** [comment]
Here is the "big ugly call" I had in mind. Not as bad as I initially thought.

Assuming `/tmp/longlines.svg` is a single-layer (i.e. single-colour) SVG with the lines to be split and `/tmp/well.svg` is the well-dipping pattern, then the following command will run `splitdist`, spread the drawing layers on even layer IDs, and load the well pattern on odd layer IDs:

```
vpype read /tmp/longlines.svg splitdist 30cm forlayer lmove %_lid% %_lid*2% read -l %_lid*2-1% /tmp/well.svg end show
```

Here is the same with multi-line formatting for readability:

```
vpype \
    read /tmp/longlines.svg \
    splitdist 30cm \
    forlayer \
        lmove %_lid% %_lid*2% \
        read -l %_lid*2-1% /tmp/well.svg \
    end \
    show
```

**Comment by abey79** [comment]
Update: I'm very close to build a single command to run the full processing given one multi-layer file and N per-colour "well" filles, but I uncovered several issues (#501). I'll work on them in the coming days and revert.

**Comment by andeecollard** [comment]
> Here is the "big ugly call" I had in mind. Not as bad as I initially thought.
> 
> Assuming `/tmp/longlines.svg` is a single-layer (i.e. single-colour) SVG with the lines to be split and `/tmp/well.svg` is the well-dipping pattern, then the following command will run `splitdist`, spread the drawing layers on even layer IDs, and load the well pattern on odd layer IDs:
> 
> ```
> vpype read /tmp/longlines.svg splitdist 30cm forlayer lmove %_lid% %_lid*2% read -l %_lid*2-1% /tmp/well.svg end show
> ```
> 
> Here is the same with multi-line formatting for readability:
> 
> ```
> vpype \
>     read /tmp/longlines.svg \
>     splitdist 30cm \
>     forlayer \
>         lmove %_lid% %_lid*2% \
>         read -l %_lid*2-1% /tmp/well.svg \
>     end \
>     show
> ```

This looks promising– what does the "%_lid%" do?

**Comment by abey79** [comment]
The `%` characters delineate an [expression](https://vpype.readthedocs.io/en/latest/fundamentals.html#expression-substitution) and `_lid` is a variable set by the [`forlayer`](https://vpype.readthedocs.io/en/latest/reference.html#forlayer) command which contains the layer ID of the layer currently processed by the block.

**Comment by abey79** [comment]
@andeecollard Still working on this and making good progress. I found yet another bug in the process of getting that command to work as expected (in `lmove` this time), which is good. I'm strengthening my tests too, especially to avoid regression with complex commands like this one in the future.

**Comment by andeecollard** [comment]
@abey79 Brilliant! I'll give it a go!

**Pull request merged**
