### PR TITLE
Add GitHub action to run tests on PRs

### PR DESCRIPTION
**Pull request by vytis**
I noticed that the repository does not have any checks added. 

It seems the tests are currently failing on master. I did a quick `git bisect` and it seems to be broken since 7b753f8154f2be46622e8f3cb400c3fa3c9dc552 - unfortunately I don't know enough about the codebase to fix the issue...

### CODE REVIEW

**Comment by vytis** [comment]
It doesn't show the checks on this PR, but it should start working after merge. It does run on my fork - https://github.com/vytis/vpype/actions

**Comment by abey79** [comment]
oOo I've been meaning to do something like this but procrastinated because it's totally new to me. Looks like it's failing on your fork though. I need to look into it.

**Comment by abey79** [comment]
I noticed you used `pip install -r requirements.txt` which currently is more for the dev env (black, etc.) and does't "install" the package. Wouldn't it make sense to rather use `pip install .`?
In that case, we'll need to `pip install pytest` manually of course.

**Comment by vytis** [comment]
Yes the checks fail, because one test fails - same happens on my computer. Not sure if I am doing something wrong there. Does it all work for you?

Regarding "installing" the package, would the behaviour be different in that case? Could it be the reason why the tests fail for me?

**Comment by abey79** [comment]
I didn't have the issue on my dev clone. I narrowed it down, it's liked to Shapely. I had 1.6.4.post2 on my dev clone, and the issue shows up with 1.7.0. I will push a fix soon.

**Comment by abey79** [comment]
As you can see, I changed to `pip install .`. My reasoning is that this way mimics more closely the end user's install process, especially in terms of dependency list.

**Comment by abey79** [comment]
All done. Thanks for the contribution, it already proved useful :)

**Pull request merged**
