### PR TITLE
added 11x14 paper size

### PR DESCRIPTION
**Pull request by zoso95**
11x14 is a pretty common paper size you see plotter people using. It doesn't have a really common paper name (the closest I found was 11r, but this creates parsing errors, so I named it r11)

### CODE REVIEW

**Comment by abey79** [comment]
Is 11x14 somewhat standard or one of an infinite list of custom sizes? In the latter case, it might be best to implement a command which accept any custom paper size.

**Comment by zoso95** [comment]
I think it would be good to have a command that does custom sizes. That being said I know Folegman uses 11x14 for his prints, and it's one of the common drawing paper sizes 

https://www.strathmoreartist.com/draw-bristol/400-series-bristol.html

**Comment by abey79** [comment]
Sounds good. Also, why `r11`? It feels like `11x14` would be a better name, esp. if some other former gets added.

**Comment by zoso95** [comment]
I haven't checked this with 11x14, but it seems like its going to throw an exception because its going to be interpreted as a unitted number (which it can't parse). I know for 11r it had issues. (also 11r is just what it is called in photo paper land)

**Comment by abey79** [comment]
I did a quick check and it works. It is not expecting a length here, just a string from a list. So for clarity I suggest we go for `11x14`. If you like, you can update your branch so I can merge it.

**Comment by zoso95** [comment]
just changed it

**Comment by abey79** [comment]
Merged, thanks!

**Pull request merged**
